// Generated by gencpp from file my_package/AddtwoInts.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_ADDTWOINTS_H
#define MY_PACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_package/AddtwoIntsRequest.h>
#include <my_package/AddtwoIntsResponse.h>


namespace my_package
{

struct AddtwoInts
{

typedef AddtwoIntsRequest Request;
typedef AddtwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddtwoInts
} // namespace my_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package::AddtwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::my_package::AddtwoInts&) { return value(); }
};

template<>
struct DataType< ::my_package::AddtwoInts > {
  static const char* value()
  {
    return "my_package/AddtwoInts";
  }

  static const char* value(const ::my_package::AddtwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_package::AddtwoIntsRequest> should match
// service_traits::MD5Sum< ::my_package::AddtwoInts >
template<>
struct MD5Sum< ::my_package::AddtwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::AddtwoInts >::value();
  }
  static const char* value(const ::my_package::AddtwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::AddtwoIntsRequest> should match
// service_traits::DataType< ::my_package::AddtwoInts >
template<>
struct DataType< ::my_package::AddtwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_package::AddtwoInts >::value();
  }
  static const char* value(const ::my_package::AddtwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package::AddtwoIntsResponse> should match
// service_traits::MD5Sum< ::my_package::AddtwoInts >
template<>
struct MD5Sum< ::my_package::AddtwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::AddtwoInts >::value();
  }
  static const char* value(const ::my_package::AddtwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::AddtwoIntsResponse> should match
// service_traits::DataType< ::my_package::AddtwoInts >
template<>
struct DataType< ::my_package::AddtwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_package::AddtwoInts >::value();
  }
  static const char* value(const ::my_package::AddtwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_ADDTWOINTS_H
